services:
  dsai-core:
    image: agentvoiceresponse/dsai-core
    platform: linux/x86_64
    container_name: dsai-core
    restart: always
    environment:
      - PORT=5001
      - ASR_URL=http://dsai-asr-google-cloud-speech:6001/speech-to-text-stream
      - LLM_URL=http://dsai-llm-openrouter:6009/prompt-stream
      - TTS_URL=http://dsai-tts-google-cloud-tts:6003/text-to-speech-stream
      - INTERRUPT_LISTENING=false
      - SYSTEM_MESSAGE=${SYSTEM_MESSAGE:-"Hello, I'm your personal assistant"}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://host.docker.internal:3001/webhooks}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-}
    ports:
      - 5001:5001
    networks:
      - dsai

  dsai-asr-google-cloud-speech:
    image: agentvoiceresponse/dsai-asr-google-cloud-speech
    platform: linux/x86_64
    container_name: dsai-asr-google-cloud-speech
    restart: always
    environment:
      - PORT=6001
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/google.json
      - SPEECH_RECOGNITION_LANGUAGE=${SPEECH_RECOGNITION_LANGUAGE:-en-US}
      - SPEECH_RECOGNITION_MODEL=telephony
    volumes:
      - ./google.json:/usr/src/app/google.json
    networks:
      - dsai

  dsai-tts-google-cloud-tts:
    image: agentvoiceresponse/dsai-tts-google-cloud-tts
    platform: linux/x86_64
    container_name: dsai-tts-google-cloud-tts
    restart: always
    environment:
      - PORT=6003
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/google.json
      - TEXT_TO_SPEECH_LANGUAGE=${TEXT_TO_SPEECH_LANGUAGE:-en-US}
      - TEXT_TO_SPEECH_GENDER=${TEXT_TO_SPEECH_GENDER:-FEMALE}
      - TEXT_TO_SPEECH_NAME=${TEXT_TO_SPEECH_NAME:-en-US-Chirp-HD-F}
      - TEXT_TO_SPEECH_SPEAKING_RATE=${TEXT_TO_SPEECH_SPEAKING_RATE:-1.0}
    volumes:
      - ./google.json:/usr/src/app/google.json
    networks:
      - dsai

  dsai-llm-openrouter:
    image: agentvoiceresponse/dsai-llm-openrouter
    platform: linux/x86_64
    container_name: dsai-llm-openrouter
    restart: always
    environment:
      - PORT=6009
      - OPENROUTER_API_KEY=$OPENROUTER_API_KEY
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.0-flash-lite-preview-02-05:free}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT:-"You are my personal assistant"}
    networks:
      - dsai

  dsai-asterisk:
    image: agentvoiceresponse/dsai-asterisk
    platform: linux/x86_64
    container_name: dsai-asterisk
    restart: always
    ports:
      - 5038:5038
      - 5060:5060
      - 8088:8088
      - 8089:8089
      - 10000-10050:10000-10050/udp
    volumes:
      - ./asterisk/conf/manager.conf:/etc/asterisk/my_manager.conf
      - ./asterisk/conf/pjsip.conf:/etc/asterisk/my_pjsip.conf
      - ./asterisk/conf/extensions.conf:/etc/asterisk/my_extensions.conf
      - ./asterisk/conf/queues.conf:/etc/asterisk/my_queues.conf
      - ./asterisk/conf/ari.conf:/etc/asterisk/my_ari.conf
    networks:
      - dsai


networks:
  dsai:
    name: dsai
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
